import { Course, User, Module, Topic, Assignment } from '@/types';

// Dummy Users
export const dummyUsers: User[] = [
  {
    id: 'admin-1',
    email: 'admin@demo.com',
    name: 'John Admin',
    role: 'admin',
    avatar: 'https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&w=64&h=64',
  },
  {
    id: 'student-1',
    email: 'student@demo.com',
    name: 'Sarah Student',
    role: 'student',
    avatar: 'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=64&h=64',
  },
];

// Dummy Topics
const dummyTopics: Topic[] = [
  {
    id: 'topic-1',
    moduleId: 'module-1',
    title: 'Introduction to React',
    description: 'Learn the basics of React components and JSX',
    type: 'video',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    videoDuration: 600,
    order: 1,
    assignments: [],
    completed: false,
    createdAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'topic-2',
    moduleId: 'module-1',
    title: 'State and Props',
    description: 'Understanding React state management and props',
    type: 'video',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    videoDuration: 720,
    order: 2,
    assignments: [],
    completed: false,
    createdAt: '2024-01-15T08:30:00Z',
  },
  {
    id: 'topic-3',
    moduleId: 'module-2',
    title: 'Node.js Fundamentals',
    description: 'Introduction to server-side JavaScript with Node.js',
    type: 'video',
    videoUrl: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    videoDuration: 900,
    order: 1,
    assignments: [],
    completed: false,
    createdAt: '2024-01-16T09:00:00Z',
  },
];

// Dummy Modules
const dummyModules: Module[] = [
  {
    id: 'module-1',
    courseId: 'course-1',
    title: 'React Fundamentals',
    description: 'Learn the core concepts of React development',
    order: 1,
    topics: dummyTopics.filter(t => t.moduleId === 'module-1'),
    createdAt: '2024-01-15T08:00:00Z',
  },
  {
    id: 'module-2',
    courseId: 'course-1',
    title: 'Backend with Node.js',
    description: 'Build server-side applications with Node.js',
    order: 2,
    topics: dummyTopics.filter(t => t.moduleId === 'module-2'),
    createdAt: '2024-01-16T09:00:00Z',
  },
];

// Dummy Courses
export const dummyCourses: Course[] = [
  {
    id: 'course-1',
    title: 'Complete React & Node.js Development',
    description: 'Master full-stack web development with React and Node.js. Build modern web applications from scratch.',
    thumbnail: 'https://images.pexels.com/photos/11035380/pexels-photo-11035380.jpeg?auto=compress&cs=tinysrgb&w=400&h=225',
    instructor: 'Alex Johnson',
    duration: '12 weeks',
    level: 'intermediate',
    price: 99.99,
    rating: 4.8,
    studentsCount: 1205,
    modules: dummyModules.filter(m => m.courseId === 'course-1'),
    createdAt: '2024-01-15T00:00:00Z',
    updatedAt: '2024-01-20T00:00:00Z',
  },
  {
    id: 'course-2',
    title: 'Python for Data Science',
    description: 'Learn Python programming and data analysis with pandas, numpy, and matplotlib.',
    thumbnail: 'https://images.pexels.com/photos/1181671/pexels-photo-1181671.jpeg?auto=compress&cs=tinysrgb&w=400&h=225',
    instructor: 'Dr. Emily Chen',
    duration: '8 weeks',
    level: 'beginner',
    price: 79.99,
    rating: 4.9,
    studentsCount: 2341,
    modules: [],
    createdAt: '2024-01-10T00:00:00Z',
    updatedAt: '2024-01-18T00:00:00Z',
  },
  {
    id: 'course-3',
    title: 'Advanced JavaScript & TypeScript',
    description: 'Deep dive into advanced JavaScript concepts and TypeScript for scalable applications.',
    thumbnail: 'https://images.pexels.com/photos/879109/pexels-photo-879109.jpeg?auto=compress&cs=tinysrgb&w=400&h=225',
    instructor: 'Michael Rodriguez',
    duration: '10 weeks',
    level: 'advanced',
    price: 129.99,
    rating: 4.7,
    studentsCount: 892,
    modules: [],
    createdAt: '2024-01-12T00:00:00Z',
    updatedAt: '2024-01-22T00:00:00Z',
  },
  {
    id: 'course-4',
    title: 'UI/UX Design Masterclass',
    description: 'Learn modern UI/UX design principles, Figma, and user research methodologies.',
    thumbnail: 'https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=400&h=225',
    instructor: 'Jessica Williams',
    duration: '6 weeks',
    level: 'beginner',
    price: 89.99,
    rating: 4.6,
    studentsCount: 1567,
    modules: [],
    createdAt: '2024-01-08T00:00:00Z',
    updatedAt: '2024-01-25T00:00:00Z',
  },
  {
    id: 'course-5',
    title: 'Machine Learning with Python',
    description: 'Build intelligent systems with scikit-learn, TensorFlow, and deep learning techniques.',
    thumbnail: 'https://images.pexels.com/photos/8386440/pexels-photo-8386440.jpeg?auto=compress&cs=tinysrgb&w=400&h=225',
    instructor: 'Dr. Robert Kim',
    duration: '14 weeks',
    level: 'advanced',
    price: 199.99,
    rating: 4.9,
    studentsCount: 756,
    modules: [],
    createdAt: '2024-01-05T00:00:00Z',
    updatedAt: '2024-01-19T00:00:00Z',
  },
  {
    id: 'course-6',
    title: 'Mobile App Development with React Native',
    description: 'Create cross-platform mobile applications using React Native and Expo.',
    thumbnail: 'https://images.pexels.com/photos/607812/pexels-photo-607812.jpeg?auto=compress&cs=tinysrgb&w=400&h=225',
    instructor: 'Lisa Thompson',
    duration: '9 weeks',
    level: 'intermediate',
    price: 109.99,
    rating: 4.5,
    studentsCount: 1034,
    modules: [],
    createdAt: '2024-01-20T00:00:00Z',
    updatedAt: '2024-01-28T00:00:00Z',
  },
];